# Generated by Django 6.0.2 on 2026-03-19 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_app', '0002_task_assigned_by_task_assigned_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectuser',
            name='role',
            field=models.CharField(choices=[('DEV', 'Developer'), ('QA', 'Qualtiy Analyst'), ('TL', 'Team Lead'), ('TST', 'Tester')], default='EMP', max_length=10),
        ),
    ]
