# Generated by Django 6.0.2 on 2026-03-04 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_app', '0003_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='company',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='companyworkspace', to='company_app.company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workspaceuser',
            name='company',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='companyworkspaceuser', to='company_app.company'),
            preserve_default=False,
        ),
    ]
