# Generated by Django 6.0.2 on 2026-03-05 02:03

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company_app', '0004_workspace_company_workspaceuser_company'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workspace',
            name='company',
        ),
        migrations.AlterUniqueTogether(
            name='workspaceuser',
            unique_together={('user', 'workspace')},
        ),
        migrations.RemoveField(
            model_name='workspaceuser',
            name='company',
        ),
        migrations.DeleteModel(
            name='Company',
        ),
    ]
