# Generated by Django 6.0.2 on 2026-03-09 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_app', '0005_remove_workspace_company_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=50)),
                ('project_description', models.CharField(max_length=500)),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('project_of_workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projectworkspace', to='company_app.workspace')),
            ],
        ),
    ]
