# Generated by Django 6.0.2 on 2026-03-11 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_app', '0006_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=50)),
                ('task_description', models.CharField(max_length=500)),
                ('status', models.CharField(choices=[('PND', 'Pending'), ('RES', 'Resolved'), ('AWT', 'Awaiting response')], default='PND', max_length=3)),
                ('priority', models.CharField(choices=[('3', 'Not so Important'), ('2', 'Important'), ('1', 'Immediate attention')], default='3', max_length=3)),
                ('completion_date', models.DateTimeField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('task_of_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taskproject', to='company_app.project')),
                ('task_of_workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taskworkspace', to='company_app.workspace')),
            ],
        ),
    ]
