# Generated by Django 6.0.2 on 2026-03-12 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_app', '0007_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_of_workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='company_app.workspace'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_of_project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='company_app.project'),
        ),
        migrations.AlterField(
            model_name='workspaceuser',
            name='role',
            field=models.CharField(choices=[('EMP', 'Employee'), ('MNG', 'Manager'), ('HOD', 'Head of the department'), ('OWN', 'Owner')], default='EMP', max_length=3),
        ),
    ]
