# Generated by Django 6.0.2 on 2026-03-12 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_app', '0008_alter_project_project_of_workspace_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workspaceuser',
            name='role',
            field=models.CharField(choices=[('EMP', 'Employee'), ('MNG', 'Manager'), ('HOD', 'Head of the department')], default='EMP', max_length=3),
        ),
    ]
